<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MBKMSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320094','Sekar Zaneta Amirul Putri','Magang Bersertifikat','PT Paragon Technology and Innovation','Jl Swadharma Raya, Kampung Baru IV No 4, Ulujami, Pesanggrahan, Jakarta Selatan 12250. Indonesia','Selesai',13);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('10320114','Yukuri Hanjani Putri','Magang Bersertifikat','PT United Tractors Tbk','Jl. Raya Bekasi No.KM.22, RT.7/RW.1, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('10320112','Ardaneshwara Gea','Magang Bersertifikat','PT Bumitama Gunajaya Agro','JL. Melawai Raya No. 10, RT.003 RW.001, Kebayoran Baru, Jakarta Selatan, DKI Jakarta Raya','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320080','Rafli Ridwan Ramadhan','Magang Bersertifikat','PT Petrokimia Gresik','Jl. Jend. Ahmad Yani, Gresik 61119, Jawa Timur','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320079','Rafi''ud Darojat','Magang Bersertifikat','Danone Indonesia (PT Tirta Investama)','Jl. Prof. DR. Satrio No.Kav.3, Karet Kuningan, Kecamatan Setiabudi, Daerah Khusus Ibukota Jakarta 12940','Selesai',19);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320083','Rahmat Herpradipto','Magang Bersertifikat','PT Industri Kereta Api (INKA)','. Yos Sudarso No. 71 Madiun 63122, Jawa Timur.','Selesai',17);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320096','Stefany Caesarya Permatasari','Magang Bersertifikat','PT Industri Kereta Api (INKA)','. Yos Sudarso No. 71 Madiun 63122, Jawa Timur.','Selesai',17);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320101','Tito Adam Perwirayudha','Magang Bersertifikat','PT Telkom Akses','Jl. Letjen S. Parman No.Kav 8, RT.1/RW.7, Tomang, Kec. Grogol petamburan, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11440','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320009','Angela Regine Mutiaraputi','Magang Bersertifikat','ASTRA (PT Mobilitas Digital Indonesia)','United Tractors Wings Area, Jl. Raya Bekasi No.KM 22, West Cakung, Cakung, East Jakarta City, Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320032','Elza Naomi Alifah Zain','Magang Bersertifikat','PT XL Axiata Tbk','Rasuna Said X5 Kav. 11-12, H.R. Rasuna Said, Rasuna Said, Jakarta Selatan.','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320026','Dhea Naomi Kenlaksita','Magang Bersertifikat','PT Global Digital Niaga (Blibli.com)','Jl. Budi Kemuliaan 1 No. 1, Gambir, Jakarta Pusat','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320019','Candrika Dewi','Magang Bersertifikat','PT United Tractors Tbk','Jl. Raya Bekasi No.KM.22, RT.7/RW.1, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320057','Mira Yunisa Amalia','Magang Bersertifikat','PT United Tractors Tbk','Jl. Raya Bekasi No.KM.22, RT.7/RW.1, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320120','Alfina Diva Ramadhanty','Magang Bersertifikat','PT United Tractors Tbk','Jl. Raya Bekasi No.KM.22, RT.7/RW.1, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320035','Ervizal Buana Jatiputra','Magang Bersertifikat','PT Paragon Technology and Innovation','Kawasan Industri Jatake Blok AG No. 8 Jalan Industri Raya IV Jatiluwung, Bunder, Kec. Cikupa, Banten 15136','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320002','Adrian Kwanadi Setiono','Magang Bersertifikat','PT Triatra Sinergia Pratama','Jl. Raya Bekasi No.KM 22, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320038','Fadhila Diah Ayu P','Magang Bersertifikat','PT Toyota Motor Manufacturing Indonesia','Jalan Laksda Yos Sudarso Sunter 1, RT.2/RW.9, Sunter Jaya, Kec. Tj. Priok, Jkt Utara, Daerah Khusus Ibukota Jakarta 14350','Selesai',17);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320107','Vincentia Putri Kharisma','Magang Bersertifikat','PT Nihon Seiki Indonesia','Jl. Angsana Raya No.2, Sukaresmi, Cikarang Sel., Kabupaten Bekasi, Jawa Barat','Selesai',14);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320010','Anisa Sulistyaningsih','Magang Bersertifikat','PT Industri Kereta Api (INKA)','Jl. Yos Sudarso No. 71 Madiun 63122, Jawa Timur.','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320013','Athallah Naufal Kur''anityo','Magang Bersertifikat','PT Industri Kereta Api (INKA)','Jl. Yos Sudarso No. 71 Madiun 63122, Jawa Timur.','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320043','Hafid Maulana Yunizar','Magang Bersertifikat','PT Paragon Technology and Innovation','Kawasan Industri Jatake Blok AG No. 8 Jalan Industri Raya IV Jatiluwung, Bunder, Kec. Cikupa, Banten 15136','Selesai',13);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320113','Yuki Rizkylawati','Magang Bersertifikat','Danone Indonesia (PT Nutricia Indonesia Sejahtera)','Jl Raya Bogor Km 26.6 13710 Jakarta Jakarta','Selesai',14);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320023','Deadila Defiatri','Magang Bersertifikat','PT Inamas Sintetis Teknologi (INASTEK)','Cupuwatu II, Purwomartani, Kec. Kalasan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55571','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320109','Wanda Aulia Abrar','Magang Bersertifikat','PT Bersama Zatta Jaya (eclorps)','Komplek Industri Prapanca, Cigondewah Kaler, Kec. Bandung Kulon, Kota Bandung, Jawa Barat 40214','Selesai',14);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320056','Maria Lavenia Vika Pamukasari','Magang Bersertifikat','Solo Technopark','Jl. Ki Hajar Dewantara No.19, Jebres, Kec. Jebres, Kota Surakarta, Jawa Tengah 57126','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320066','Muhammad Jefri Saputra','Magang Bersertifikat','PT Bintang Teodjjo (a Kalbe Company)','Pulo Gadung Industrial Estate K.9, Jl. Rw. Gelam V No.9, Jatinegara, Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13920','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320003','Afiq Ramadhan','Magang Bersertifikat','PT Bukit Makmur Mandiri Utama','South Quarter Tower A, Lantai Penthause, Unit A-1 Jl. R.A Kartini Kav. 8 Cilandak Barat Jakarta selatan 12430','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320051','Ilham Fairuzaman','Magang Bersertifikat','PT United Tractors Tbk','Jl. Raya Bekasi No.KM.22, RT.7/RW.1, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320040','Fajri Nur Hidayah','Magang Bersertifikat','PT Paragon Technology and Innovation','Jl Swadharma Raya, Kampung Baru IV No 4, Ulujami, Pesanggrahan, Jakarta Selatan 12250. Indonesia','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320018','Bonang Respati Satmoko','Magang Bersertifikat','PT United Tractors Tbk','Jl. Raya Bekasi No.KM.22, RT.7/RW.1, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320017','Berlian Safri Prakoso','Magang Bersertifikat','PT XL Axiata Tbk','Jl. H. R. Rasuna Said No.Kav 11-12, RT.7/RW.2, Kuningan, Kuningan Tim., Kecamatan Setiabudi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12950','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320093','Sekar Salsabila Santosa','Magang Bersertifikat','PT XL Axiata Tbk','Jl. H. R. Rasuna Said No.Kav 11-12, RT.7/RW.2, Kuningan, Kuningan Tim., Kecamatan Setiabudi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12950','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320052','Ilham Maulana Nur Afani','Magang Bersertifikat','PT Triatra Sinergia Pratama','Jl. Raya Bekasi No.KM.22, RT.7/RW.1, Cakung Bar., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910','Selesai',11);");
        DB::statement("INSERT INTO mbkm(nim,nama,status,perusahaan,alamat,status_selesai,rekognisi_sks) VALUES ('I0320092','Salsabila Rana Fadhilah','Magang Bersertifikat','PT Toyota Motor Manufacturing Indonesia','Jalan Laksda Yos Sudarso  10, RT.10/RW.6, sungai bambub, Kec.Tj. Priok, JKt Utara, DKI Jakarta 14330','Selesai',11);");
    }
}
